services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: membersite
    volumes:
      - member_site_pg:/var/lib/postgresql/data

volumes:
  member_site_pg:
